# Generated by Django 5.2.14 on 2026-05-13 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="crews",
            field=models.ManyToManyField(to="airport.crew"),
        ),
    ]
