# Generated by Django 5.2.14 on 2026-05-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_route_destination_alter_route_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "flight")},
        ),
    ]
