# Generated by Django 5.2.14 on 2026-05-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ("seat",)},
        ),
    ]
