# Generated by Django 5.2.14 on 2026-05-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_ticket_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created",)},
        ),
    ]
