# Generated by Django 5.2.14 on 2026-05-22 17:54

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_alter_order_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.airplane_image_path
            ),
        ),
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.crew_image_path
            ),
        ),
    ]
