# Generated by Django 5.2.14 on 2026-05-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0009_alter_airport_closest_big_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="closest_big_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="airports",
                to="airport.city",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="airline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="airport.airline",
            ),
        ),
    ]
