# Generated by Django 5.2.14 on 2026-05-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0010_alter_airport_closest_big_city_alter_flight_airline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
    ]
