# Generated by Django 5.2.14 on 2026-05-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0011_alter_city_options_alter_country_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
