# Generated by Django 5.2.14 on 2026-05-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0012_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
