# Generated by Django 5.2.14 on 2026-05-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0013_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="crews",
            field=models.ManyToManyField(
                blank=True, related_name="flights", to="airport.crew"
            ),
        ),
    ]
